### ISSUE TITLE
Null Pointer on select DVR after delete all storage and uninstall then reinstall

### ISSUE THREAD

**Issue by tekrantz** [MythTV-Clients/MythTV-Android-Frontend#157] opened 2013-08-27 22:13 UTC
If I clear everything for myth android frontend and start it up, add a home profile and then select DVR I get a null pointer exception.

stack:

mythtv-android-frontend [Android Application]  
    DalvikVM[localhost:8600]  
        Thread [<1> main](Suspended %28exception RuntimeException%29)  
            ActivityThread.performLaunchActivity(ActivityThread$ActivityClientRecord, Intent) line: 1968  
            ActivityThread.handleLaunchActivity(ActivityThread$ActivityClientRecord, Intent) line: 1993 
            ActivityThread.access$600(ActivityThread, ActivityThread$ActivityClientRecord, Intent) line: 127  
            ActivityThread$H.handleMessage(Message) line: 1159  
            ActivityThread$H(Handler).dispatchMessage(Message) line: 99 
            Looper.loop() line: 137 
            ActivityThread.main(String[]) line: 4512  
            Method.invokeNative(Object, Object[], Class, Class[], Class, int, boolean) line: not available [native method]  
            Method.invoke(Object, Object...) line: 511  
            ZygoteInit$MethodAndArgsCaller.run() line: 978  
            ZygoteInit.main(String[]) line: 745 
            NativeStart.main(String[]) line: not available [native method]  
        Thread [<10> Binder Thread #2](Running)  
        Thread [<9> Binder Thread #1](Running) 
        Daemon Thread [<8> FinalizerWatchdogDaemon](Running)  
        Daemon Thread [<7> FinalizerDaemon](Running)  
        Daemon Thread [<6> ReferenceQueueDaemon](Running)  
        Thread [<11> Binder Thread #3](Running)  
        Thread [<12> pool-2-thread-1](Running) 
        Thread [<13> AsyncTask #1](Running)  
        Thread [<14> AsyncTask #2](Running)  
        Thread [<15> AsyncTask #3](Running)  
        Thread [<16> Binder Thread #4](Running)  
        Thread [<17> Binder Thread #5](Running)  
        Thread [<18> Binder Thread #6](Running)  
        Thread [<19> Binder Thread #7](Running)  
        Thread [<20> Binder Thread #8](Running)  
        Thread [<21> Binder Thread #9](Running)  
        Thread [<22> Binder Thread #10](Running)  
        Thread [<23> Binder Thread #11](Running)  
        Thread [<25> Binder Thread #13](Running)  
        Thread [<24> Binder Thread #12](Running)   

Logcat message:

08-27 18:13:44.555: W/dalvikvm(11328): threadid=1: thread exiting with uncaught exception (group=0x40c401f8)
08-27 18:13:44.635: E/AndroidRuntime(11328): FATAL EXCEPTION: main
08-27 18:13:44.635: E/AndroidRuntime(11328): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mythtv/org.mythtv.client.ui.dvr.DvrNavigationDrawerActivity}: java.lang.NullPointerException
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1968)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1993)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.app.ActivityThread.access$600(ActivityThread.java:127)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1159)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.os.Handler.dispatchMessage(Handler.java:99)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.os.Looper.loop(Looper.java:137)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.app.ActivityThread.main(ActivityThread.java:4512)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at java.lang.reflect.Method.invokeNative(Native Method)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at java.lang.reflect.Method.invoke(Method.java:511)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at dalvik.system.NativeStart.main(Native Method)
08-27 18:13:44.635: E/AndroidRuntime(11328): Caused by: java.lang.NullPointerException
08-27 18:13:44.635: E/AndroidRuntime(11328):    at org.mythtv.client.ui.dvr.ProgramGroupFragment.onCreateLoader(ProgramGroupFragment.java:93)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:490)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:499)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManager.java:553)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at org.mythtv.client.ui.dvr.ProgramGroupFragment.onActivityCreated(ProgramGroupFragment.java:156)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1486)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1460)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.Fragment.performStart(Fragment.java:1499)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:957)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1882)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:573)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1136)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.app.Activity.performStart(Activity.java:4479)
08-27 18:13:44.635: E/AndroidRuntime(11328):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1941)
08-27 18:13:44.635: E/AndroidRuntime(11328):    ... 11 more

**Comment by billmeek** [comment] 2013-08-27 22:44
Appears to be a duplicate of #153. If you disagree, please comment and I'll re-open it
(or you can too.) In either case, thanks for testing!

```
FYI, if you start your LogCat with <pre> and and end it with </pre>, you'll get 
entries in the issues list that don't have folded lines. It will look like this paragraph.
```

PS, no sirs here, just friendly folks interested in the project. ;)

**Closed as completed by billmeek** 2013-08-27 22:44 UTC
Labels: duplicate
