### ISSUE TITLE
Recordings won't play after changing playback profile

### ISSUE THREAD

**Issue by Prefect47** [MythTV-Clients/MythTV-Android-Frontend#27] opened 2012-07-02 08:42 UTC
If I have played a recording using 720p and then try to play the same with 540p, it plays for less than one second and then exits. The same happens with the profiles the other way around. 

I'm using the 2012-06-30 apk and BSPlayer lite.

This may be an API issue.

**Comment by dmfrey** [comment] 2012-07-06 20:16
@Prefect47 it has come to our attention that HLS is broken currently in the myth backend.  That may be causing the issue you are referring to.  There has been a lot of chatter on the mailing lists regarding this issue lately.

**Comment by dmfrey** [comment] 2012-07-18 12:45
@Prefect47 Can you try this again with the latest development build and provide any feedback.  If there is no further issue, please close the issue.  Thanks,

**Comment by dmfrey** [comment] 2012-10-08 00:08
@Prefect47 no update on this issue. Closing for now.  If the issue is still occurring, please re-open the ticket and update with your findings.

**Closed as completed by dmfrey** 2012-10-08 00:08 UTC
Labels: bug
