### ISSUE TITLE
Recordings rules: Unfortunately, MythTV Android Frontend has stopped

### ISSUE THREAD

**Issue by xavierh** [MythTV-Clients/MythTV-Android-Frontend#73] opened 2012-11-12 13:54 UTC
It does happen every time I enter into Recordings Rules via Home or Away  (ssh)

**Comment by dmfrey** [comment] 2012-11-12 13:57
This is currently being address.  The force close has been addressed in git
and the remaining functionality is currently being worked for editing these
rules.

Thank you for your input.

On Mon, Nov 12, 2012 at 8:54 AM, xavierh notifications@github.com wrote:

> It does happen every time I enter into Recordings Rules via Home or Away
> (ssh)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/73.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by jmturner** [comment] 2012-12-29 03:56
Hmm. My Myth backend is up (as verified by my Ubuntu client, yet my MAF 1.0.4 on my Lenovo K1 crashes when I click on Recordings. Running Android 3.2.1. (Unfortunately, I don't have any debug logs as I don't have USB support set up in Ubuntu for this tablet yet.) Myth backend is 2:0.25.2+fixes

**Comment by billmeek** [comment] 2013-01-26 03:41
@jmturner, a fix was just added to the development version to treat errors
in the MythTV database. Can you try this command and look for "odd" time
stamps in the output please?

```
.  ~/.mythtv/mysql.txt
mysql -umythtv -p$DBPassword mythconverg -e \
    "SELECT title,progstart,progend FROM recorded ORDER BY starttime"
```

In the issue just fixed, progend was 00-00-00T00:00:00.

**Comment by jmturner** [comment] 2013-01-26 16:35
@billmeek, my progend entries all have normal values.
[snip]
| Masterpiece Classic | 2013-01-23 16:00:00 | 2013-01-23 17:30:00 |
| NOVA                | 2013-01-23 21:00:00 | 2013-01-23 22:00:00 |

 It doesn't look like this is the same issue.

**Comment by billmeek** [comment] 2013-01-26 16:50
@jmturner, thanks for checking.

If you're willing to let me access your backend via port 6544,
I can test this from my tablet and capture program flow with Android 
debugging tools. Contact me off list if you're interested. Spell my name
backwards and use gmail.

**Comment by billmeek** [comment] 2013-01-27 00:02
Worked off list with @jmturner. This _may_ be MythTV data specific.

Closing this and re-opening #90 to track the Recording screen failure.

**Closed as completed by billmeek** 2013-01-27 00:02 UTC

**Comment by dmfrey** [comment] 2013-01-27 15:12
Attempted to reproduce first with network available, then with network not available.  Could not reproduce the issue.
